import { useState, useEffect } from 'react';
import { loginUser } from './authService';
import { useAuth } from '../../context/AuthContext';
import { useNavigate, Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Mail, Lock, AlertCircle, ArrowRight, Loader2, Eye, EyeOff, CheckCircle2 } from 'lucide-react';

const LoginPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeText, setActiveText] = useState(0);

  const taglines = [
    {
      title: "AI-Powered Learning Roadmaps",
      desc: "Get personalized, interactive career maps generated by AI based on your experience and dream goals."
    },
    {
      title: "Level Up with Verified Skills",
      desc: "Complete challenges, build real portfolio projects, and earn XP that showcases your competency to recruiters."
    },
    {
      title: "Expert Mentorship On-Demand",
      desc: "Connect directly with experienced engineers and designers from tech giants like Google, Meta, and Netflix."
    }
  ];

  // Rotate taglines
  useEffect(() => {
    const timer = setInterval(() => {
      setActiveText((prev) => (prev + 1) % taglines.length);
    }, 4500);
    return () => clearInterval(timer);
  }, [taglines.length]);

  // Pre-fill email from query parameter if available
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const emailParam = params.get('email');
    if (emailParam) {
      setEmail(emailParam);
    }
  }, [location]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      console.log('LoginPage - Attempting to login with:', { email });
      const response = await loginUser({ email, password });
      console.log('LoginPage - Login response:', response);
      
      const { token, user } = response;
      console.log('LoginPage - Extracted user data:', user);
      
      // First, call login with the basic user data
      login(user, token);
      
      // Then, fetch the user's profile
      console.log('LoginPage - Fetching user profile...');
      const apiBase = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';
      const profileResponse = await fetch(`${apiBase}/api/user/profile`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      
      if (!profileResponse.ok) {
        throw new Error('Failed to fetch user profile');
      }
      
      const profileData = await profileResponse.json();
      console.log('LoginPage - Fetched profile data:', profileData);
      
      // Update the user with the profile data
      login({ ...user, profile: profileData }, token);
      
      console.log('LoginPage - After login() with profile, navigating to /dashboard');
      navigate('/dashboard');
    } catch (errMsg) {
      console.error('LoginPage - Login error:', errMsg);
      setError(errMsg?.message || errMsg || 'Login failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-black text-white flex items-center justify-center lg:grid lg:grid-cols-12 relative overflow-hidden">
      {/* Background Ambient Glows */}
      <div className="absolute inset-0 -z-20 pointer-events-none">
        <div className="absolute w-[500px] h-[500px] bg-purple-500/5 rounded-full blur-[140px] top-1/4 left-1/3" />
        <div className="absolute w-[400px] h-[400px] bg-blue-500/5 rounded-full blur-[120px] bottom-1/4 right-1/3" />
      </div>

      {/* Left Branding Panel (hidden on mobile, visible on desktop) */}
      <div className="hidden lg:flex lg:col-span-5 xl:col-span-6 flex-col justify-between p-12 h-screen relative overflow-hidden border-r border-zinc-900 bg-zinc-950/40 shrink-0">
        {/* Fine-mesh Tech Grid */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808003_1px,transparent_1px),linear-gradient(to_bottom,#80808003_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none" />
        
        {/* Cosmic Background Nebulae */}
        <div className="absolute top-[-20%] left-[-20%] w-[80%] h-[80%] bg-purple-500/10 rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[70%] h-[70%] bg-blue-500/10 rounded-full blur-[120px] pointer-events-none" />
        
        {/* Logo Header */}
        <Link to="/" className="flex items-center gap-2.5 group self-start z-10">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-purple-500 to-blue-500 flex items-center justify-center shadow-lg shadow-purple-500/20 group-hover:scale-105 transition-transform duration-300">
            <span className="text-white font-black text-sm">SM</span>
          </div>
          <span className="font-black text-xl tracking-wider group-hover:text-purple-400 transition-colors">
            SKILL<span className="text-[#8C49E9]">MENTOR</span>
          </span>
        </Link>

        {/* Visual Roadmap Simulation Centerpiece */}
        <div className="relative flex flex-col justify-center gap-6 pl-10 my-auto z-10 max-w-md mx-auto w-full">
          {/* Vertical Connecting Line */}
          <div className="absolute left-[23px] top-6 bottom-6 w-[2px] bg-gradient-to-b from-emerald-500 via-[#8C49E9] to-zinc-800" />

          {/* Node 1: Completed */}
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="relative flex items-center gap-4 bg-zinc-900/30 backdrop-blur-md border border-emerald-500/20 rounded-2xl p-4 shadow-lg hover:border-emerald-500/40 transition-all duration-300 group/node cursor-pointer"
          >
            <div className="w-8 h-8 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 z-10 shrink-0 group-hover/node:scale-105 transition-transform">
              <CheckCircle2 className="w-4 h-4" />
            </div>
            <div>
              <h4 className="text-sm font-semibold text-white group-hover/node:text-emerald-400 transition-colors">Frontend Fundamentals</h4>
              <p className="text-xs text-gray-400">Completed • Earned 800 XP</p>
            </div>
          </motion.div>

          {/* Node 2: Active */}
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            className="relative flex items-center gap-4 bg-zinc-900/60 backdrop-blur-md border border-[#8C49E9]/40 rounded-2xl p-4 shadow-[0_0_20px_rgba(140,73,233,0.15)] z-10 hover:border-[#8C49E9] transition-all duration-300 group/node2 cursor-pointer"
          >
            <div className="absolute -inset-[1px] rounded-2xl bg-gradient-to-r from-purple-500 to-blue-500 opacity-20 blur-sm animate-pulse pointer-events-none" />
            <div className="w-8 h-8 rounded-full bg-[#8C49E9]/20 border border-[#8C49E9] flex items-center justify-center text-[#8C49E9] z-10 shrink-0 relative group-hover/node2:scale-105 transition-transform">
              <span className="w-2 h-2 bg-[#8C49E9] rounded-full animate-ping absolute" />
              <div className="w-3.5 h-3.5 rounded-full bg-[#8C49E9] flex items-center justify-center">
                <span className="text-[9px] text-white font-bold">2</span>
              </div>
            </div>
            <div>
              <h4 className="text-sm font-bold text-white group-hover/node2:text-purple-400 transition-colors">React & Framer Motion UI</h4>
              <p className="text-xs text-purple-400 font-medium">Active Roadmap Node</p>
            </div>
          </motion.div>

          {/* Node 3: Locked */}
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.6 }}
            className="relative flex items-center gap-4 bg-zinc-900/10 border border-zinc-800/60 rounded-2xl p-4 opacity-60 hover:opacity-95 hover:border-zinc-700 transition-all duration-300 cursor-not-allowed group/node3"
          >
            <div className="w-8 h-8 rounded-full bg-zinc-900 border border-zinc-800 flex items-center justify-center text-zinc-500 z-10 shrink-0 group-hover/node3:rotate-12 transition-transform">
              <Lock className="w-3.5 h-3.5" />
            </div>
            <div>
              <h4 className="text-sm font-semibold text-gray-400">Career Strategy & Placement</h4>
              <p className="text-xs text-gray-500">Locked • Unlock at Level 5</p>
            </div>
          </motion.div>
        </div>

        {/* Dynamic Taglines Area */}
        <div className="mb-8 z-10 max-w-md mx-auto w-full">
          <div className="min-h-[85px]">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeText}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -12 }}
                transition={{ duration: 0.35 }}
              >
                <h3 className="text-lg font-bold bg-gradient-to-r from-white via-gray-100 to-gray-300 bg-clip-text text-transparent mb-1.5">
                  {taglines[activeText].title}
                </h3>
                <p className="text-sm text-gray-400 font-light leading-relaxed">
                  {taglines[activeText].desc}
                </p>
              </motion.div>
            </AnimatePresence>
          </div>
          
          {/* Tagline dots indicators */}
          <div className="flex gap-2 mt-4">
            {taglines.map((_, idx) => (
              <button 
                key={idx}
                onClick={() => setActiveText(idx)}
                className={`h-1 rounded-full transition-all duration-300 cursor-pointer ${idx === activeText ? 'w-5 bg-[#8C49E9]' : 'w-1.5 bg-zinc-800 hover:bg-zinc-700'}`}
              />
            ))}
          </div>
        </div>

        {/* Metrics Footer Section */}
        <div className="grid grid-cols-3 gap-6 pt-6 border-t border-zinc-900/60 z-10 max-w-md mx-auto w-full">
          <div>
            <div className="text-lg font-black text-white">24K+</div>
            <div className="text-[9px] text-gray-500 font-semibold tracking-wider uppercase">Paths Mapped</div>
          </div>
          <div>
            <div className="text-lg font-black text-white">98.4%</div>
            <div className="text-[9px] text-gray-500 font-semibold tracking-wider uppercase">Mastery Rate</div>
          </div>
          <div>
            <div className="text-lg font-black text-white">150+</div>
            <div className="text-[9px] text-gray-500 font-semibold tracking-wider uppercase">Expert Mentors</div>
          </div>
        </div>
      </div>

      {/* Right Panel (Authentication Form Panel) */}
      <div className="lg:col-span-7 xl:col-span-6 flex flex-col justify-center items-center p-6 md:p-12 w-full h-full min-h-screen lg:h-screen overflow-y-auto relative z-10">
        
        {/* Mobile Header Logo */}
        <div className="lg:hidden flex items-center gap-2.5 mb-8">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-purple-500 to-blue-500 flex items-center justify-center shadow-lg shadow-purple-500/20">
            <span className="text-white font-black text-sm">SM</span>
          </div>
          <span className="font-black text-xl tracking-wider text-white">
            SKILL<span className="text-[#8C49E9]">MENTOR</span>
          </span>
        </div>

        {/* Glassmorphic Form Card Wrapper */}
        <motion.div
          initial={{ opacity: 0, scale: 0.96 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ type: "spring", stiffness: 100, damping: 15 }}
          className="w-full max-w-md p-[1px] rounded-3xl bg-zinc-800/40 hover:bg-gradient-to-b hover:from-purple-500/25 hover:to-blue-500/25 transition-all duration-500 shadow-2xl relative group"
        >
          {/* Card Ambient Glow Background */}
          <div className="absolute -inset-0.5 rounded-3xl bg-gradient-to-tr from-purple-600/10 to-blue-600/10 opacity-30 blur-lg group-hover:opacity-50 transition-all duration-500 pointer-events-none" />

          <div className="relative p-8 md:p-10 rounded-[23px] bg-zinc-950/85 backdrop-blur-2xl border border-zinc-900/60 overflow-hidden flex flex-col justify-between">
            {/* Tech Grid Background inside card */}
            <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808003_1px,transparent_1px),linear-gradient(to_bottom,#80808003_1px,transparent_1px)] bg-[size:20px_20px] pointer-events-none" />

            <div className="relative z-10">
              <h2 className="text-2xl font-black tracking-tight text-white mb-1.5">
                Welcome Back
              </h2>
              <p className="text-gray-400 text-xs font-light mb-6">
                Sign in to access your customized learning paths and connect with mentors.
              </p>

              {/* Social Logins */}
              <div className="grid grid-cols-2 gap-3 mb-6">
                <button
                  type="button"
                  className="flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-zinc-900/80 border border-zinc-800/80 hover:bg-zinc-850 hover:border-zinc-700 transition-all duration-300 text-xs font-semibold text-gray-300 hover:text-white cursor-pointer select-none"
                >
                  <svg className="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12.24 10.285V14.4h6.887c-.648 2.41-2.519 4.114-5.136 4.114A5.728 5.728 0 0 1 8.24 12.8a5.728 5.728 0 0 1 5.751-5.714c1.5 0 2.861.567 3.9 1.493l3.053-3.053C19.068 3.821 16.7 2.8 13.99 2.8A9.71 9.71 0 0 0 4.28 12.5a9.71 9.71 0 0 0 9.71 9.7 9.4 9.4 0 0 0 9.71-9.7c0-.685-.06-1.303-.171-1.915H12.24Z" />
                  </svg>
                  <span>Google</span>
                </button>
                <button
                  type="button"
                  className="flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl bg-zinc-900/80 border border-zinc-800/80 hover:bg-zinc-850 hover:border-zinc-700 transition-all duration-300 text-xs font-semibold text-gray-300 hover:text-white cursor-pointer select-none"
                >
                  <svg className="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="currentColor">
                    <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.603-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.464-1.11-1.464-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.831.092-.646.35-1.086.636-1.336-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.577.688.479C19.138 20.164 22 16.418 22 12c0-5.523-4.477-10-10-10z" />
                  </svg>
                  <span>GitHub</span>
                </button>
              </div>

              {/* Divider */}
              <div className="relative flex items-center justify-center my-5">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-zinc-900"></div>
                </div>
                <span className="relative px-3 text-[10px] uppercase font-bold text-gray-500 bg-zinc-950/85 tracking-wider select-none">
                  or sign in with email
                </span>
              </div>

              {/* Error Message */}
              {error && (
                <motion.div 
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-red-500/10 border border-red-500/20 text-red-400 p-3.5 rounded-xl text-xs flex gap-2 items-center mb-5"
                >
                  <AlertCircle className="w-4 h-4 flex-shrink-0" />
                  <span>{error}</span>
                </motion.div>
              )}

              {/* Form */}
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider select-none">
                    Email Address
                  </label>
                  <div className="relative flex items-center bg-zinc-900/40 border border-zinc-800/80 rounded-xl focus-within:border-[#8C49E9] focus-within:ring-2 focus-within:ring-[#8C49E9]/20 transition-all duration-300 shadow-[inset_0_2px_4px_rgba(0,0,0,0.6)] group/input">
                    <Mail className="absolute left-4 text-gray-500 w-4 h-4 group-focus-within/input:text-[#8C49E9] transition-colors" />
                    <input
                      type="email"
                      placeholder="name@example.com"
                      className="w-full pl-12 pr-4 py-3 bg-transparent border-0 outline-none text-white placeholder-gray-600 text-sm focus:ring-0"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider select-none">
                    Password
                  </label>
                  <div className="relative flex items-center bg-zinc-900/40 border border-zinc-800/80 rounded-xl focus-within:border-[#8C49E9] focus-within:ring-2 focus-within:ring-[#8C49E9]/20 transition-all duration-300 shadow-[inset_0_2px_4px_rgba(0,0,0,0.6)] group/input">
                    <Lock className="absolute left-4 text-gray-500 w-4 h-4 group-focus-within/input:text-[#8C49E9] transition-colors" />
                    <input
                      type={showPassword ? 'text' : 'password'}
                      placeholder="••••••••"
                      className="w-full pl-12 pr-12 py-3 bg-transparent border-0 outline-none text-white placeholder-gray-600 text-sm focus:ring-0"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-4 text-gray-500 hover:text-white transition-colors cursor-pointer select-none"
                    >
                      {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                <div className="flex items-center justify-between text-xs text-gray-400 py-1">
                  <label className="flex items-center gap-2 cursor-pointer select-none hover:text-gray-300 transition-colors">
                    <input 
                      type="checkbox" 
                      className="rounded border-zinc-800 bg-zinc-900 text-[#8C49E9] focus:ring-[#8C49E9]/40 accent-[#8C49E9] w-4 h-4"
                    />
                    <span>Remember me</span>
                  </label>
                  <Link to="#" className="hover:text-[#8C49E9] hover:underline transition-colors font-medium">
                    Forgot password?
                  </Link>
                </div>

                <motion.button
                  type="submit"
                  disabled={isLoading}
                  whileHover={{ scale: 1.01 }}
                  whileTap={{ scale: 0.99 }}
                  className={`w-full py-3.5 rounded-xl font-bold text-white transition-all shadow-lg flex items-center justify-center gap-2 text-sm cursor-pointer mt-2 relative overflow-hidden group/btn
                    ${isLoading
                      ? 'bg-zinc-800 text-zinc-500 border border-zinc-700 cursor-not-allowed'
                      : 'bg-[#8C49E9] hover:bg-[#7a3cd1] hover:shadow-[#8C49E9]/30 hover:shadow-xl'}
                  `}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin text-zinc-500" />
                      <span>Signing in...</span>
                    </>
                  ) : (
                    <>
                      <span>Sign In</span>
                      <ArrowRight className="w-4.5 h-4.5 group-hover/btn:translate-x-0.5 transition-transform" />
                    </>
                  )}
                </motion.button>
              </form>
            </div>

            {/* Footer Link */}
            <div className="text-center mt-8 relative z-10">
              <span className="text-xs text-gray-500 font-light">New to SkillMentor? </span>
              <Link to="/register" className="text-xs text-[#8C49E9] font-bold hover:text-[#7a3cd1] transition hover:underline">
                Create a free account
              </Link>
            </div>
            
            {/* Corner Indicator */}
            <div className="absolute top-4 right-4 w-2 h-2 rounded-full bg-gradient-to-tr from-purple-500 to-blue-400 opacity-0 group-hover:opacity-100 transition-opacity" />
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default LoginPage;
